steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile.prod',
      '-t', 'europe-north1-docker.pkg.dev/buoyant-idea-458413-p8/custom-fastapi/custom-fastapi:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-north1-docker.pkg.dev/buoyant-idea-458413-p8/custom-fastapi/custom-fastapi:latest'
    ]

images:
  - 'europe-north1-docker.pkg.dev/buoyant-idea-458413-p8/custom-fastapi/custom-fastapi:latest'


