steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'Dockerfile.prod',
      '-t', 'europe-north2-docker.pkg.dev/buoyant-idea-458413-p8/dvml6-deployment/dvml6-deployment:latest',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'europe-north2-docker.pkg.dev/buoyant-idea-458413-p8/dvml6-deployment/dvml6-deployment:latest'
    ]

images:
  - 'europe-north2-docker.pkg.dev/buoyant-idea-458413-p8/dvml6-deployment/dvml6-deployment:latest'


