apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dvml6-deployment-service
spec:
  template:
    spec:
      containers:
        - image: europe-north2-docker.pkg.dev/buoyant-idea-458413-p8/dvml6-deployment/dvml6-deployment:latest
          env: []
          ports:
            - containerPort: 4000